const { app, BrowserWindow, ipcMain, globalShortcut } = require('electron');
const path = require('path');
const { spawn } = require('child_process');
const fs = require('fs');
const http = require('http');
const { pathToFileURL } = require('url');
const { setupApplicationMenu } = require('./menu.cjs');

function tryEnsureWritableDir(dirPath) {
  try {
    fs.mkdirSync(dirPath, { recursive: true });
  } catch {
    return false;
  }

  try {
    const test = path.join(dirPath, `.write_test_${Date.now()}_${Math.random().toString(16).slice(2)}`);
    fs.writeFileSync(test, 'ok');
    fs.unlinkSync(test);
    return true;
  } catch {
    return false;
  }
}

/**
 * ✅ PRINT GUARDIAN (EXE)
 * En production, garantit que PrintQueueGuardian.ps1 existe et démarre automatiquement.
 * Objectif: éviter les jobs bloqués dans printer\*.json (spooler/FS watchers capricieux).
 */
function findBundledSumatraExe() {
  const candidates = [];
  try {
    if (process.resourcesPath) {
      // resources/app.asar.unpacked/node_modules/pdf-to-printer/dist/SumatraPDF-*.exe
      const unpacked = path.join(process.resourcesPath, 'app.asar.unpacked');
      candidates.push(
        path.join(unpacked, 'node_modules', 'pdf-to-printer', 'dist', 'SumatraPDF-3.4.6-32.exe'),
        path.join(unpacked, 'node_modules', 'pdf-to-printer', 'dist', 'SumatraPDF.exe'),
        path.join(process.resourcesPath, 'vendor', 'sumatra', 'SumatraPDF.exe'),
      );
    }
  } catch {}

  for (const p of candidates) {
    try { if (p && fs.existsSync(p)) return p; } catch {}
  }
  return '';
}

function buildPrintQueueGuardianScript({ printDir, sumatraExe }) {
  const rootEsc = String(printDir || '').replace(/\\/g, '\\\\');
  const sumatraEsc = String(sumatraExe || '').replace(/\\/g, '\\\\');

  return (
`# PrintQueueGuardian.ps1 - LA GRACE POS (AUTO)
# Generated by electron/main.cjs
$ErrorActionPreference = "SilentlyContinue"

$Root = "${rootEsc}"
$SumatraPath = "${sumatraEsc}"

function Write-Log([string]$Level, [string]$Message) {
  try {
    $logDir = Join-Path $Root "logs"
    if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir -Force | Out-Null }
    $logFile = Join-Path $logDir ("guardian-" + (Get-Date -Format 'yyyy-MM-dd') + ".log")
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$ts] [$Level] $Message"
    Add-Content -Path $logFile -Value $line -ErrorAction SilentlyContinue
  } catch {}
}

Write-Log "INFO" "Guardian start. Root=$Root Sumatra=$SumatraPath"

try {
  $svc = Get-Service -Name Spooler -ErrorAction Stop
  if ($svc.Status -ne "Running") {
    Start-Service Spooler -ErrorAction Stop
    Write-Log "INFO" "Spooler started"
  }
} catch {
  Write-Log "WARN" ("Spooler check failed: " + $_.Exception.Message)
}

$ok  = Join-Path $Root "ok"
$err = Join-Path $Root "err"
$tmp = Join-Path $Root "tmp"
@($Root, $ok, $err, $tmp) | ForEach-Object { if (-not (Test-Path $_)) { New-Item -ItemType Directory -Path $_ -Force | Out-Null } }

while ($true) {
  try {
    $files = Get-ChildItem -Path $Root -File -ErrorAction SilentlyContinue |
      Where-Object {
        ($_.Extension -eq ".json" -or $_.Extension -eq ".pdf") -and
        $_.FullName -notlike "$ok*" -and $_.FullName -notlike "$err*" -and $_.FullName -notlike "$tmp*" -and
        $_.FullName -notlike "*\\logs\\*"
      }

    foreach ($f in $files) {
      $age = (New-TimeSpan -Start $f.LastWriteTime -End (Get-Date)).TotalSeconds
      if ($age -ge 10) {
        $tmpName = "$($f.FullName).poke"
        try {
          Rename-Item -Path $f.FullName -NewName $tmpName -ErrorAction Stop
          Start-Sleep -Milliseconds 120
          Rename-Item -Path $tmpName -NewName $f.FullName -ErrorAction Stop
          Write-Log "WARN" ("Poke: " + $f.Name + " age=" + [math]::Round($age) + "s")
        } catch {
          Write-Log "WARN" ("Poke failed: " + $f.Name + " - " + $_.Exception.Message)
        }
      }
    }
  } catch {
    Write-Log "ERROR" ("Loop error: " + $_.Exception.Message)
  }

  Start-Sleep -Seconds 2
}
`
  );
}

function ensureAndStartPrintGuardian() {
  try {
    if (!app.isPackaged) return; // uniquement EXE
    if (process.platform !== 'win32') return;

    // ✅ CHEMIN FIXE: C:\Glowflixprojet (pas userData)
    const FIXED_DATA_ROOT = 'C:\\Glowflixprojet';
    const printerDir = path.join(FIXED_DATA_ROOT, 'printer');
    const guardianRoot = FIXED_DATA_ROOT;
    const psPath = path.join(guardianRoot, 'PrintQueueGuardian.ps1');
    const sumatraExe = findBundledSumatraExe();

    console.log(`[PRINT][GUARDIAN] 📁 Dossier printer: ${printerDir}`);
    console.log(`[PRINT][GUARDIAN] 📁 Script guardian: ${psPath}`);
    console.log(`[PRINT][GUARDIAN] 🖨️  SumatraPDF: ${sumatraExe || 'non trouvé'}`);

    // ✅ Créer l'arborescence printer/ (PRO) au démarrage
    try { fs.mkdirSync(printerDir, { recursive: true }); } catch {}
    try { fs.mkdirSync(path.join(printerDir, 'ok'), { recursive: true }); } catch {}
    try { fs.mkdirSync(path.join(printerDir, 'err'), { recursive: true }); } catch {}
    try { fs.mkdirSync(path.join(printerDir, 'tmp'), { recursive: true }); } catch {}
    try { fs.mkdirSync(path.join(printerDir, 'logs'), { recursive: true }); } catch {}
    try { fs.mkdirSync(path.join(printerDir, 'templates'), { recursive: true }); } catch {}
    try { fs.mkdirSync(path.join(printerDir, 'assets'), { recursive: true }); } catch {}

    // ✅ Copier templates/assets par défaut si absents (premier démarrage EXE)
    try {
      const resourcesRoot = resolveResourcesRoot();
      const packagedTemplates = path.join(resourcesRoot, 'print', 'templates');
      const packagedAssets = path.join(resourcesRoot, 'print', 'assets');
      const dstTemplates = path.join(printerDir, 'templates');
      const dstAssets = path.join(printerDir, 'assets');

      if (fs.existsSync(packagedTemplates)) {
        for (const name of fs.readdirSync(packagedTemplates)) {
          const src = path.join(packagedTemplates, name);
          const dst = path.join(dstTemplates, name);
          try {
            if (!fs.existsSync(dst) && fs.statSync(src).isFile()) fs.copyFileSync(src, dst);
          } catch {}
        }
      }

      if (fs.existsSync(packagedAssets)) {
        for (const name of fs.readdirSync(packagedAssets)) {
          const src = path.join(packagedAssets, name);
          const dst = path.join(dstAssets, name);
          try {
            if (!fs.existsSync(dst) && fs.statSync(src).isFile()) fs.copyFileSync(src, dst);
          } catch {}
        }
      }
    } catch {}

    const content = buildPrintQueueGuardianScript({ printDir: printerDir, sumatraExe });
    let needWrite = true;
    try {
      if (fs.existsSync(psPath)) {
        const cur = fs.readFileSync(psPath, 'utf-8');
        if (cur && cur.includes('PrintQueueGuardian.ps1 - LA GRACE POS (AUTO)') && cur.includes(printerDir)) {
          needWrite = false;
        }
      }
    } catch {}

    if (needWrite) {
      try { fs.writeFileSync(psPath, content, 'utf-8'); } catch {}
      logToFile('[PRINT][GUARDIAN] script written:', psPath);
    } else {
      logToFile('[PRINT][GUARDIAN] script already ok:', psPath);
    }

    // Lancer en arrière-plan (sans bloquer)
    try {
      const p = spawn('powershell.exe', ['-NoProfile', '-WindowStyle', 'Hidden', '-ExecutionPolicy', 'Bypass', '-File', psPath], {
        windowsHide: true,
        detached: true,
        stdio: 'ignore',
        shell: false,
      });
      p.unref();
      logToFile('[PRINT][GUARDIAN] started pid=' + String(p.pid || 'n/a'));
    } catch (e) {
      logToFile('[PRINT][GUARDIAN] start failed: ' + (e?.message || e));
    }
  } catch (e) {
    try { logToFile('[PRINT][GUARDIAN] ensure failed: ' + (e?.message || e)); } catch {}
  }
}

/**
 * ✅ LOGGING FICHIER CRITIQUE
 * Écrit les logs IMPORTANTS dans un fichier pour diagnostic EXE
 * (ne pas se fier aux DevTools fermées en production)
 */
const LOG_DIR = (() => {
  // ⚠️ IMPORTANT: app.getPath('userData') peut throw avant app "ready".
  // On fallback vers %APPDATA% pour éviter que l'EXE ne se ferme silencieusement.
  try {
    return path.join(app.getPath('userData'), 'logs');
  } catch {
    const appData = process.env.APPDATA || path.join(process.env.USERPROFILE || 'C:\\Users\\Default', 'AppData', 'Roaming');
    return path.join(appData, 'LA GRACE POS', 'logs');
  }
})();
try { fs.mkdirSync(LOG_DIR, { recursive: true }); } catch {}
const MAIN_LOG = path.join(LOG_DIR, 'main.log');
const AI_STDOUT = path.join(LOG_DIR, 'ai-stdout.log');
const AI_STDERR = path.join(LOG_DIR, 'ai-stderr.log');

function logToFile(...args) {
  const ts = new Date().toISOString();
  const msg = args.map(a => {
    if (a instanceof Error) return `${a.message}\n${a.stack}`;
    if (typeof a === 'object') return JSON.stringify(a);
    return String(a);
  }).join(' ');
  try { fs.appendFileSync(MAIN_LOG, `[${ts}] ${msg}\n`); } catch {}
}

function getExeStatusPath() {
  try {
    return path.join(LOG_DIR, 'exe-status.json');
  } catch {
    return '';
  }
}

function writeExeStatus(patch) {
  try {
    const p = getExeStatusPath();
    if (!p) return;
    let cur = {};
    try {
      if (fs.existsSync(p)) {
        const raw = fs.readFileSync(p, 'utf-8');
        cur = raw ? JSON.parse(raw) : {};
      }
    } catch {}

    const next = {
      ...cur,
      ...patch,
      ts: new Date().toISOString(),
      isPackaged: !!app.isPackaged,
      nodeEnv: process.env.NODE_ENV,
      appRoot: process.env.APP_ROOT,
      resourcesRoot: process.env.RESOURCES_ROOT,
      dataRoot: process.env.LAGRACE_DATA_DIR,
    };
    fs.writeFileSync(p, JSON.stringify(next, null, 2), 'utf-8');
  } catch {}
}

// Double log: console + fichier pour les events critiques
function logCritical(...args) {
  console.log('[CRITICAL]', ...args);
  logToFile('[CRITICAL]', ...args);
}

// Gérer les erreurs non capturées - TRÈS IMPORTANT en EXE
process.on('uncaughtException', (error) => {
  logCritical('🔴 UNCAUGHT EXCEPTION:', error.message);
  if (error.stack) logToFile(error.stack);
  console.error('🔴 UNCAUGHT EXCEPTION:', error);
});

process.on('unhandledRejection', (reason, promise) => {
  logCritical('🔴 UNHANDLED REJECTION:', reason?.message || reason);
  if (reason?.stack) logToFile(reason.stack);
  console.error('🔴 UNHANDLED REJECTION:', reason);
});

/**
 * ✅ HELPERS DE RÉSOLUTION DE CHEMINS ROBUSTES
 * Évite les erreurs "resources/app.asar/resources" en prod
 */
function resolveResourcesRoot() {
  const env = (process.env.RESOURCES_ROOT || '').trim();
  if (env) return env;

  // En prod, c'est la valeur la plus fiable
  if (process.resourcesPath && String(process.resourcesPath).trim()) {
    return process.resourcesPath;
  }

  // Fallback sûr: parent de app.asar
  return path.dirname(app.getAppPath());
}

function resolveAppRoot() {
  // APP_ROOT = app.asar (ou project root en dev)
  const env = (process.env.APP_ROOT || '').trim();
  if (env) return env;
  return app.getAppPath();
}

let serverProcess = null;
let aiProcess = null;
let mainWindow = null;
let appContext = null; // Contexte app (paths, db, etc.)

/**
 * Envoyer un statut de l'IA à la fenêtre principale
 */
function sendAIStatus(status, message = '') {
  if (mainWindow && mainWindow.webContents) {
    console.log(`[IPC] Envoi du statut AI: ${status}`);
    mainWindow.webContents.send('ai-status-update', { status, message });
  }
}
const PORT = process.env.PORT || 3030;
const HOST = '127.0.0.1';  // ✅ Utiliser IPv4 explicite pour éviter les problèmes IPv6
const SERVER_URL = `http://${HOST}:${PORT}`;

// Configuration AI LaGrace
const AI_ENABLED = process.env.AI_LAGRACE_ENABLED !== 'false';

// ✅ En DEV: l'IA est déjà lancée par concurrently (npm run dev:electron / dev:app)
// ✅ En PROD (EXE): Electron doit lancer ai-lagrace.exe
const AI_AUTOSTART = app.isPackaged
  ? (AI_ENABLED && process.env.AI_LAGRACE_AUTOSTART !== 'false')
  : false;

// ✅ CHEMIN AI
const AI_DIR = app.isPackaged
  ? path.join(process.resourcesPath, 'ai')        // Production: resources/ai
  : path.join(__dirname, '..', 'ai-lagrace');     // Dev: project/ai-lagrace

// ✅ EXE en prod directement dans resources/ai (pas de sous-dossier)
const AI_MAIN = app.isPackaged
  ? path.join(AI_DIR, 'ai-lagrace.exe')           // ✅ CORRECT: resources/ai/ai-lagrace.exe
  : path.join(AI_DIR, 'main.py');                 // Dev: ai-lagrace/main.py

/**
 * Vérifier si Python (venv) est disponible
 */
function checkPython() {
  return new Promise((resolve) => {
    const pythonExe = process.platform === 'win32' 
      ? path.join(__dirname, '..', '.venv', 'Scripts', 'python.exe')
      : path.join(__dirname, '..', '.venv', 'bin', 'python');
    
    // 1️⃣ Vérifier si le fichier existe
    if (!fs.existsSync(pythonExe)) {
      console.log(`[AI] Python non trouvé au chemin: ${pythonExe}`);
      resolve(false);
      return;
    }
    
    // 2️⃣ Le fichier existe, vérifier si c'est un fichier valide
    try {
      const stats = fs.statSync(pythonExe);
      if (stats.isFile()) {
        console.log(`[AI] Python trouvé: ${pythonExe} (${stats.size} bytes)`);
        // 3️⃣ Essayer de lancer Python pour une confirmation finale
        const check = spawn(pythonExe, ['--version'], { 
          shell: false,  // ❌ Changer à false pour éviter les problèmes avec les chemins avec espaces
          timeout: 5000,
          stdio: ['ignore', 'pipe', 'pipe']
        });
        
        let output = '';
        check.stdout.on('data', (data) => {
          output += data.toString();
        });
        check.stderr.on('data', (data) => {
          output += data.toString();
        });
        
        const timeout = setTimeout(() => {
          check.kill();
          console.log(`[AI] Timeout lors de la vérification Python`);
          resolve(false);
        }, 5000);
        
        check.on('close', (code) => {
          clearTimeout(timeout);
          if (code === 0) {
            console.log(`[AI] Python fonctionne: ${output.trim()}`);
            resolve(true);
          } else {
            console.log(`[AI] Python existe mais sortie d'erreur: ${output}`);
            // Malgré l'erreur, le fichier existe, donc on considère que Python est disponible
            resolve(true);
          }
        });
        
        check.on('error', (err) => {
          clearTimeout(timeout);
          console.log(`[AI] Erreur spawn Python: ${err.message}`);
          // Le fichier existe, donc considérer que Python est disponible
          resolve(true);
        });
      } else {
        console.log(`[AI] ${pythonExe} n'est pas un fichier`);
        resolve(false);
      }
    } catch (e) {
      console.log(`[AI] Erreur vérification Python: ${e.message}`);
      resolve(false);
    }
  });
}

/**
 * Démarrer AI LaGrace (Python)
 * ⚠️ NE PAS relancer l'IA si elle est déjà lancée par npm run dev (concurrently)
 * L'IA reste active en permanence et ne se déconnecte pas automatiquement
 */
async function startAI() {
  if (!AI_ENABLED) {
    console.log('[AI] AI LaGrace désactivée par configuration');
    return;
  }
  
  // ✅ CORRECTION: NE PAS relancer l'IA si elle est déjà en cours d'exécution
  // En développement (npm run dev), concurrently lance DÉJÀ l'IA
  // Relancer ici causait deux instances parlant en même temps (doublons audio)
  
  if (!AI_AUTOSTART) {
    console.log('[AI] AI LaGrace gérée par le serveur (autostart désactivé)');
    return;
  }
  
  // ✅ CONTRÔLE: Vérifier si l'IA est DÉJÀ en cours d'exécution sur le port/socket
  const checkAIRunning = new Promise((resolve) => {
    const req = http.get('http://localhost:3030/api/ai/status', { timeout: 2000 }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          resolve(json.running === true);
        } catch (e) {
          resolve(false);
        }
      });
    });
    req.on('error', () => resolve(false));
    req.on('timeout', () => {
      req.destroy();
      resolve(false);
    });
  });

  try {
    const aiIsRunning = await checkAIRunning;
    if (aiIsRunning) {
      console.log('[AI] ========================================');
      console.log('[AI] ℹ️  AI LAGRACE DÉJÀ EN COURS D\'EXÉCUTION');
      console.log('[AI] ========================================');
      console.log('[AI] Une instance de l\'IA est déjà active (lancée par concurrently)');
      console.log('[AI] Pas besoin de la relancer via Electron');
      sendAIStatus('connected', 'IA en cours d\'exécution (serveur)');
      return;
    }
  } catch (e) {
    // Pas de réponse du serveur - continuer avec le démarrage local
    console.log('[AI] Vérification du statut AI impossible, tentative de démarrage...');
  }

  // ✅ DÉTECTION: En production (app.isPackaged), utiliser ai-lagrace.exe
  const isDev = !app.isPackaged;
  let aiCmd;
  let aiArgs;

  if (isDev) {
    // En développement: utiliser Python + main.py
    aiCmd = process.platform === 'win32' 
      ? path.join(__dirname, '..', '.venv', 'Scripts', 'python.exe')
      : path.join(__dirname, '..', '.venv', 'bin', 'python');
    aiArgs = ['main.py', '--quiet'];
    
    if (!fs.existsSync(AI_MAIN)) {
      console.log('[AI] Script Python non trouvé:', AI_MAIN);
      return;
    }

    const hasPython = await checkPython();
    if (!hasPython) {
      console.log('[AI] Python non disponible en développement');
      return;
    }
  } else {
    // En production: utiliser ai-lagrace.exe (compilé)
    aiCmd = AI_MAIN;
    aiArgs = ['--quiet'];
    
    if (!fs.existsSync(aiCmd)) {
      console.log('[AI] ❌ ERREUR: ai-lagrace.exe non trouvée en production!');
      console.log('[AI] Chemin attendu:', aiCmd);
      console.log('[AI] Vérifiez que le build est correct et que ai-lagrace.exe est dans:', AI_DIR);
      sendAIStatus('error', 'AI executable non trouvée');
      return;
    }

    console.log('[AI] ✅ ai-lagrace.exe trouvée en production');
  }

  console.log('[AI] ========================================');
  console.log(isDev ? '[AI] DÉMARRAGE DE AI LaGrace (Dev - Python)...' : '[AI] DÉMARRAGE DE AI LaGrace (Prod - EXE)...');
  console.log('[AI] Commande:', aiCmd);
  console.log('[AI] Arguments:', aiArgs);
  console.log('[AI] ========================================');

  sendAIStatus('reconnecting', 'Démarrage de l\'IA...');

  // ✅ Ouvrir les fichiers de log AI (append mode)
  const out = fs.openSync(AI_STDOUT, 'a');
  const err = fs.openSync(AI_STDERR, 'a');

  // ✅ Écrire le header de démarrage
  const startTime = new Date().toISOString();
  fs.appendFileSync(AI_STDOUT, `\n\n═══════════════════════════════════════════════════════\n[${startTime}] Démarrage AI LaGrace\n═══════════════════════════════════════════════════════\n`);
  fs.appendFileSync(AI_STDERR, `\n\n═══════════════════════════════════════════════════════\n[${startTime}] Démarrage AI LaGrace (stderr)\n═══════════════════════════════════════════════════════\n`);

  logToFile('[AI] SPAWN', {
    aiCmd,
    aiArgs,
    cwd: path.dirname(aiCmd),
    stdout: AI_STDOUT,
    stderr: AI_STDERR,
  });

  aiProcess = spawn(aiCmd, aiArgs, {
    cwd: path.dirname(aiCmd),  // ✅ IMPORTANT: cwd = répertoire où se trouve l'exe/script
    shell: false,  // ✅ Important: false pour éviter les problèmes avec les espaces
    windowsHide: true,
    stdio: ['ignore', out, err],  // ✅ Rediriger directement vers les fichiers
    env: {
      ...process.env,
      PYTHONUNBUFFERED: '1', // Force Python à ne pas bufferer la sortie
      PYTHONIOENCODING: 'utf-8', // Encodage UTF-8 pour Windows
    },
  });

  aiProcess.on('close', (code) => {
    console.log(`[AI] AI LaGrace arrêtée (code: ${code})`);
    sendAIStatus('disconnected', `IA déconnectée (code: ${code})`);
    
    // Si l'AI s'arrête de façon inattendue, la redémarrer (sauf si code 0 ou arrêt volontaire)
    if (code !== 0 && code !== null && aiProcess !== null) {
      console.log('[AI] Redémarrage automatique dans 5 secondes...');
      sendAIStatus('reconnecting', 'Tentative de redémarrage de l\'IA...');
      aiProcess = null;
      setTimeout(() => {
        if (mainWindow && !mainWindow.isDestroyed()) {
          startAI().catch((err) => {
            console.error('[AI] Erreur au redémarrage:', err);
            sendAIStatus('disconnected', 'Échec du redémarrage de l\'IA.');
          });
        }
      }, 5000);
    } else {
      aiProcess = null;
    }
  });

  aiProcess.on('error', (err) => {
    console.error('[AI] Erreur process:', err);
    aiProcess = null;
    sendAIStatus('error', `Erreur process: ${err.message}`);
  });

  console.log('[AI] AI LaGrace démarrée avec PID:', aiProcess.pid);
  console.log('[AI] L\'AI va maintenant écouter et parler...');
}

/**
 * Arrêter AI LaGrace
 */
function stopAI() {
  if (aiProcess) {
    console.log('[AI] Arrêt de AI LaGrace...');
    
    if (process.platform === 'win32') {
      spawn('taskkill', ['/pid', aiProcess.pid.toString(), '/f', '/t'], { shell: true });
    } else {
      aiProcess.kill('SIGTERM');
    }
    
    aiProcess = null;
  }
}

/**
 * Vérifier si le serveur est déjà en cours d'exécution
 */
function checkServerRunning() {
  return new Promise((resolve) => {
    const req = http.get(`${SERVER_URL}/api/health`, { timeout: 1000 }, (res) => {
      resolve(true);
    });
    req.on('error', () => {
      resolve(false);
    });
    req.on('timeout', () => {
      req.destroy();
      resolve(false);
    });
  });
}

/**
 * ✅ ROBUSTE: Démarrer le backend IN-PROCESS (importation directe du module ESM)
 * Zéro spawn, zéro chemins virtuels app.asar
 */
let backendHandle = null;

async function startBackendInProcess() {
  if (backendHandle) {
    return backendHandle;
  }

  try {
    const appRoot = resolveAppRoot();
    const resourcesRoot = resolveResourcesRoot();

    const serverJs = path.join(appRoot, 'src', 'api', 'server.js');
    const staticDir = path.join(resourcesRoot, 'ui');

    if (!fs.existsSync(serverJs)) throw new Error(`server.js introuvable: ${serverJs}`);

    // ✅ CHEMIN FIXE: C:\Glowflixprojet pour DEV et EXE
    const FIXED_DATA_ROOT = 'C:\\Glowflixprojet';
    tryEnsureWritableDir(FIXED_DATA_ROOT);
    tryEnsureWritableDir(path.join(FIXED_DATA_ROOT, 'printer'));
    tryEnsureWritableDir(path.join(FIXED_DATA_ROOT, 'db'));
    tryEnsureWritableDir(path.join(FIXED_DATA_ROOT, 'logs'));

    // Configurer l'environnement Electron
    process.env.ELECTRON_RUN_AS_NODE = '1';
    process.env.LAGRACE_IS_ELECTRON = '1';
    process.env.AI_LAGRACE_AUTOSTART = 'false';
    process.env.LAGRACE_DATA_DIR = FIXED_DATA_ROOT; // ✅ FIXE: C:\Glowflixprojet
    process.env.NODE_ENV = 'production'; // ✅ Assurer le mode production

    console.log(`[BACKEND] 📁 LAGRACE_DATA_DIR = ${FIXED_DATA_ROOT}`);

    const mod = await import(pathToFileURL(serverJs).href);
    if (!mod.startBackend) throw new Error(`server.js n'exporte pas startBackend()`);

    backendHandle = await mod.startBackend({
      port: Number(PORT),
      host: HOST,
      staticDir,
      isElectron: true,
      appRoot,
      resourcesPath: resourcesRoot,
    });

    console.log('[ELECTRON] ✅ Backend démarré');
    return backendHandle;
  } catch (error) {
    console.error('[ELECTRON] ❌ Erreur backend:', error.message);
    backendHandle = null;
    throw error;
  }
}

/**
 * Obtenir le chemin du serveur backend en fonction du mode (dev ou production)
 * ✅ En production EXE: utilise server-entry.cjs (wrapper ESM)
 * ✅ En dev: utilise server.js directement
 */
function getBackendEntry() {
  if (!app.isPackaged) {
    return path.join(__dirname, '../src/api/server.js');
  }

  const appRoot = resolveAppRoot();
  const wrapperPath = path.join(appRoot, 'src', 'api', 'server-entry.cjs');
  const serverPath = path.join(appRoot, 'src', 'api', 'server.js');

  if (fs.existsSync(wrapperPath)) return wrapperPath;
  if (fs.existsSync(serverPath)) return serverPath;
  return wrapperPath;
}

/**
 * Démarrer le serveur Node.js avec Electron en mode Node
 */
function startServer() {
  return new Promise(async (resolve, reject) => {
    // Mode développement: serveur lancé par npm run dev (concurrently)
    if (process.env.SKIP_BACKEND_WAIT === 'true') {
      setTimeout(() => resolve(), 2000);
      return;
    }

    // Vérifier d'abord si le serveur est déjà en cours d'exécution
    const isRunning = await checkServerRunning();
    if (isRunning) {
      resolve();
      return;
    }

    const serverPath = getBackendEntry();
    
    if (!fs.existsSync(serverPath)) {
      reject(new Error(`Serveur introuvable: ${serverPath}`));
      return;
    }

    const cwd = path.dirname(serverPath);

    serverProcess = spawn(process.execPath, [serverPath], {
      cwd,
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe'],
      shell: false,
      env: {
        ...process.env,
        ELECTRON_RUN_AS_NODE: '1',
        NODE_ENV: app.isPackaged ? 'production' : 'development',
        PORT: PORT.toString(),
        HOST: '127.0.0.1',
        APP_ROOT: resolveAppRoot(),
        RESOURCES_ROOT: resolveResourcesRoot(),
        LAGRACE_DATA_DIR: app.getPath('userData'),
        LAGRACE_IS_ELECTRON: '1',
        AI_LAGRACE_AUTOSTART: 'false',
      },
    });

    serverProcess.stdout.on('data', () => {});
    serverProcess.stderr.on('data', () => {});

    serverProcess.on('error', (error) => {
      reject(error);
    });

    serverProcess.on('exit', (code) => {
      if (code !== null && code !== 0 && code !== 130) {
        setTimeout(() => {
          startServer().catch(() => {});
        }, 2000);
      }
    });

    // Attendre /api/health
    waitForServer(40).then(ok => {
      if (ok) {
        resolve();
      } else {
        reject(new Error('Backend timeout'));
      }
    }).catch(reject);
  });
}

/**
 * Vérifier si le serveur répond
 */
async function waitForServer(maxAttempts = 60) {
  const checkDevServer = process.env.NODE_ENV === 'development';
  const devServerUrl = 'http://localhost:5173';
  
  for (let i = 0; i < maxAttempts; i++) {
    try {
      // Vérifier le serveur backend
      await new Promise((resolve, reject) => {
        const req = http.get(`${SERVER_URL}/api/health`, (res) => {
          if (res.statusCode === 200) {
            resolve(true);
          } else {
            reject(new Error(`Status: ${res.statusCode}`));
          }
        });
        
        req.on('error', reject);
        req.setTimeout(1000, () => {
          req.destroy();
          reject(new Error('Timeout'));
        });
      });
      
      // En mode dev, vérifier aussi Vite
      if (checkDevServer) {
        try {
          await new Promise((resolve, reject) => {
            const req = http.get(devServerUrl, (res) => {
              resolve(true);
            });
            req.on('error', reject);
            req.setTimeout(1000, () => {
              req.destroy();
              reject(new Error('Timeout'));
            });
          });
        } catch (error) {
          // Vite pas encore prêt, continuer à attendre
          await new Promise((resolve) => setTimeout(resolve, 500));
          continue;
        }
      }
      
      return true;
    } catch (error) {
      // Serveur pas encore prêt, continuer
    }
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  return false;
}

/**
 * Créer la fenêtre principale
 */
function createWindow() {
  try {
    console.log('[WINDOW] Création de la fenêtre BrowserWindow...');
    
    mainWindow = new BrowserWindow({
      width: 1400,
      height: 900,
      minWidth: 1200,
      minHeight: 700,
      icon: path.join(__dirname, '../asset/image/icon/photo.png'),
      webPreferences: {
        preload: path.join(__dirname, 'preload.cjs'),
        nodeIntegration: false,
        contextIsolation: true,
        enableRemoteModule: false,
        webSecurity: true,
      },
      titleBarStyle: 'default',
      show: false, // ✅ Ne pas montrer immédiatement pour éviter les problèmes
      backgroundColor: '#1a1a2e',
    });

    console.log('[WINDOW] BrowserWindow créée avec succès, ID:', mainWindow.id);
    
    // Afficher la fenêtre après un court délai (évite les crashes au démarrage)
    mainWindow.once('ready-to-show', () => {
      console.log('[WINDOW] Fenêtre ready-to-show');
      mainWindow.show();
    });
    
    // Fallback: afficher après 1 seconde si ready-to-show ne se déclenche pas
    setTimeout(() => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        console.log('[WINDOW] Affichage forcé de la fenêtre (fallback)');
        mainWindow.show();
      }
    }, 1000);
    
    // Focus sur la fenêtre
    if (process.platform === 'darwin') {
      app.dock.show();
    }

    // Charger l'application directement (le serveur est déjà vérifié avant createWindow)
    // En mode développement, utiliser Vite dev server
    if (process.env.NODE_ENV === 'development') {
      console.log('[WINDOW] Mode dev: Chargement de http://localhost:5173...');
      writeExeStatus({ ui: { mode: 'dev', lastAttemptUrl: 'http://127.0.0.1:5173' } });
      mainWindow.loadURL('http://127.0.0.1:5173').catch((error) => {
        console.error('[WINDOW] ❌ Erreur chargement Vite:', error);
        writeExeStatus({ ui: { mode: 'dev', lastError: String(error?.message || error), lastErrorAt: new Date().toISOString() } });
        // Fallback vers le serveur backend
        console.log('[WINDOW] Fallback: Chargement de ' + SERVER_URL);
        writeExeStatus({ ui: { mode: 'dev', lastAttemptUrl: SERVER_URL, fallback: true } });
        mainWindow.loadURL(SERVER_URL);
      });
    } else {
      console.log('[WINDOW] Mode prod: Chargement de ' + SERVER_URL);
      writeExeStatus({ ui: { mode: 'prod', lastAttemptUrl: SERVER_URL } });
      mainWindow.loadURL(SERVER_URL).catch((error) => {
        console.error('[WINDOW] ❌ Erreur chargement serveur:', error);
        writeExeStatus({ ui: { mode: 'prod', lastError: String(error?.message || error), lastErrorAt: new Date().toISOString() } });
        // Fallback vers UI en resources pour EXE
        const uiIndex = path.join(resolveResourcesRoot(), 'ui', 'index.html');
        if (fs.existsSync(uiIndex)) {
          console.log('[WINDOW] Fallback: loadFile UI:', uiIndex);
          writeExeStatus({ ui: { mode: 'prod', lastAttemptUrl: `file://${uiIndex}`, fallback: true } });
          mainWindow.loadFile(uiIndex);
        }
      });
    }

    // Ouvrir DevTools en mode développement
    if (process.env.NODE_ENV === 'development') {
      console.log('[WINDOW] Ouverture des DevTools');
      mainWindow.webContents.openDevTools();
    }

    // Gestion des erreurs de chargement
    mainWindow.webContents.on('did-fail-load', (event, errorCode, errorDescription, validatedURL) => {
      console.error(`[WINDOW] ❌ Erreur chargement (${errorCode}): ${errorDescription}`);
      console.error(`[WINDOW] URL: ${validatedURL}`);

      writeExeStatus({
        ui: {
          ...(typeof validatedURL === 'string' ? { lastFailUrl: validatedURL } : {}),
          lastFailCode: errorCode,
          lastFailDescription: errorDescription,
          lastFailAt: new Date().toISOString(),
        }
      });
      
      if (errorCode === -106 || errorCode === -105 || errorCode === -102) {
        // ERR_INTERNET_DISCONNECTED, ERR_ADDRESS_UNREACHABLE, ERR_CONNECTION_REFUSED
        console.log('[WINDOW] Tentative de rechargement dans 2 secondes...');
        setTimeout(() => {
          if (mainWindow && !mainWindow.isDestroyed()) {
            mainWindow.reload();
          }
        }, 2000);
      } else {
        // Pour d'autres erreurs, réessayer avec l'autre URL
        console.log('[WINDOW] Tentative avec URL alternative...');
        if (process.env.NODE_ENV === 'development' && validatedURL && validatedURL.includes('5173')) {
          setTimeout(() => {
            if (mainWindow && !mainWindow.isDestroyed()) {
              console.log('[WINDOW] Chargement de l\'URL alternative:', SERVER_URL);
              mainWindow.loadURL(SERVER_URL);
            }
          }, 2000);
        } else if (validatedURL && validatedURL.includes('3030')) {
          setTimeout(() => {
            if (mainWindow && !mainWindow.isDestroyed()) {
              console.log('[WINDOW] Chargement de l\'URL alternative: http://localhost:5173');
              mainWindow.loadURL('http://127.0.0.1:5173');
            }
          }, 2000);
        }
      }
    });
    
    // Log quand la page est chargée avec succès
    mainWindow.webContents.on('did-finish-load', () => {
      console.log('[WINDOW] ✅ Page chargée avec succès');
      try {
        const currentUrl = mainWindow?.webContents?.getURL?.();
        writeExeStatus({ ui: { loadedUrl: currentUrl || null, loadedAt: new Date().toISOString() } });
      } catch {}
    });

    mainWindow.on('closed', () => {
      console.log('[WINDOW] Fenêtre fermée');
      mainWindow = null;
    });
    
    // ✅ Configurer le menu de l'application
    try {
      setupApplicationMenu(mainWindow);
      console.log('[MENU] ✅ Menu application configuré');
    } catch (menuError) {
      console.error('[MENU] ❌ Erreur configuration menu:', menuError);
    }
    
    console.log('[WINDOW] ✅ Création de fenêtre complétée');
    
  } catch (error) {
    console.error('[WINDOW] ❌ ERREUR CRITIQUE création fenêtre:', error);
    console.error('[WINDOW] Stack:', error.stack);
    throw error;
  }
}

/**
 * Quand l'application est prête
 */
app.whenReady().then(async () => {
  try {
    // 🔍 DIAGNOSTIC: Log très détaillé du démarrage
    console.log('\n');
    console.log('════════════════════════════════════════════════════════════════════');
    console.log('🚀 DÉMARRAGE DE LA GRACE POS');
    console.log('════════════════════════════════════════════════════════════════════');
    logCritical('🚀 DÉMARRAGE DE LA GRACE POS');
    
    console.log(`📅 Heure: ${new Date().toISOString()}`);
    console.log(`💻 Platform: ${process.platform}`);
    console.log(`📦 Version Electron: ${require('electron').app.getVersion()}`);
    console.log(`🔒 Mode: ${app.isPackaged ? 'PRODUCTION (packaged)' : 'DEVELOPMENT'}`);
    console.log(`📂 CWD: ${process.cwd()}`);
    console.log(`📂 __dirname: ${__dirname}`);
    console.log(`📂 app.getAppPath(): ${app.getAppPath()}`);
    console.log(`📂 process.resourcesPath: ${process.resourcesPath || '(undefined)'}`);
    console.log(`📄 Log file: ${MAIN_LOG}`);
    console.log('════════════════════════════════════════════════════════════════════\n');
    
    logCritical(`Mode: ${app.isPackaged ? 'PRODUCTION' : 'DEVELOPMENT'}`);
    logCritical(`CWD: ${process.cwd()}`);
    logCritical(`appPath: ${app.getAppPath()}`);
    logCritical(`resourcesPath: ${process.resourcesPath}`);
    logCritical(`Log file: ${MAIN_LOG}`);
    
    // ✅ IMPORTANT: Définir les variables d'environnement AVANT l'initialisation
    // Point clé : APP_ROOT ≠ RESOURCES_ROOT
    // APP_ROOT = ...\resources\app.asar (prod) → où se trouve le code d'app (src/, electron/)
    // RESOURCES_ROOT = ...\resources (prod) → où se trouvent ui/, print/, config.env, ai/, etc.
    const appRootPath = resolveAppRoot();
    const resourcesRootPath = resolveResourcesRoot();
    
    process.env.APP_ROOT = appRootPath;
    process.env.RESOURCES_ROOT = resourcesRootPath;
    process.env.NODE_ENV = app.isPackaged ? 'production' : 'development';
    
    // ✅ Flag Electron
    process.env.LAGRACE_IS_ELECTRON = '1';
    
    // ✅ CHEMIN DATA FIXE: C:\Glowflixprojet (identique DEV et EXE)
    const FIXED_DATA_ROOT = 'C:\\Glowflixprojet';
    
    // Créer le dossier s'il n'existe pas
    try {
      if (!fs.existsSync(FIXED_DATA_ROOT)) {
        fs.mkdirSync(FIXED_DATA_ROOT, { recursive: true });
      }
      // Créer les sous-dossiers essentiels
      ['db', 'printer', 'printer/ok', 'printer/err', 'printer/tmp', 'logs'].forEach(sub => {
        const dir = path.join(FIXED_DATA_ROOT, sub);
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
      });
      process.env.LAGRACE_DATA_DIR = FIXED_DATA_ROOT;
      logToFile(`[PATHS] ✅ LAGRACE_DATA_DIR: ${FIXED_DATA_ROOT}`);
    } catch (e) {
      // Fallback userData si C:\ bloqué
      const userDataDir = app.getPath('userData');
      process.env.LAGRACE_DATA_DIR = userDataDir;
      logToFile(`[PATHS] ⚠️ Fallback userData: ${userDataDir}`);
    }
    
    console.log('📍 CHEMINS DÉFINIS:');
    console.log(`   APP_ROOT: ${process.env.APP_ROOT}`);
    console.log(`   RESOURCES_ROOT: ${process.env.RESOURCES_ROOT}`);
    console.log(`   LAGRACE_DATA_DIR: ${process.env.LAGRACE_DATA_DIR}`);

    // ✅ AUTO: démarrage du Guardian d'impression (EXE) le plus tôt possible
    try {
      ensureAndStartPrintGuardian();
    } catch (e) {
      logToFile('[PRINT][GUARDIAN] startup hook failed: ' + (e?.message || e));
    }
    
    // Vérification des fichiers clés
    console.log('\n🔍 VÉRIFICATION DES FICHIERS CRITIQUES:');
    const criticalFiles = [
      { name: 'server.js (ESM)', path: path.join(appRootPath, 'src', 'api', 'server.js') },
      { name: 'server-entry.cjs (wrapper)', path: path.join(appRootPath, 'src', 'api', 'server-entry.cjs') },
      { name: 'src/package.json (ESM)', path: path.join(appRootPath, 'src', 'package.json') },
      { name: 'UI (index.html)', path: path.join(resourcesRootPath, 'ui', 'index.html') },
      { name: 'UI assets', path: path.join(resourcesRootPath, 'ui', 'assets') },
      { name: 'main.cjs (app init)', path: path.join(__dirname, 'main.cjs') },
    ];
    
    for (const file of criticalFiles) {
      const exists = fs.existsSync(file.path);
      const status = exists ? '✅' : '❌';
      console.log(`   ${status} ${file.name}: ${file.path}`);
      logToFile(`[CHECK] ${status} ${file.name}: ${file.path}`);
    }
    console.log('');
    
    // Initialiser l'app (chemins, db, loggers, etc.)
    console.log('🚀 Initialisation Glowflixprojet...');
    const initBridge = require('./init-bridge.cjs');
    appContext = await initBridge.initializeApp();
    console.log('✓ Glowflixprojet contexte prêt\n');
    
    // Initialiser les handlers IPC
    const { initializeIpcHandlers } = require('./ipc-handlers.cjs');
    initializeIpcHandlers(appContext);
    
    // En mode développement, ne pas démarrer le serveur (déjà lancé par npm run dev)
    if (process.env.NODE_ENV === 'development') {
      console.log('Mode développement : utilisation du serveur externe');
      // Le script wait-and-launch-electron.js a déjà vérifié que les serveurs sont prêts
      // On peut créer la fenêtre immédiatement, mais on vérifie rapidement en arrière-plan
      
      // ✅ IMPORTANT: Créer la fenêtre SYNCHRONE (très rapide) pour éviter que Electron ne quitte
      try {
        createWindow();
        console.log('✅ Fenêtre créée avec succès');
      } catch (windowError) {
        console.error('❌ Erreur création fenêtre:', windowError);
        mainWindow = null;
      }
      
      // Vérification rapide en arrière-plan (non bloquante)
      waitForServer(5).then((ready) => {
        if (!ready) {
          console.warn('⚠️ Les serveurs ne répondent pas encore, mais la fenêtre est créée');
        }
      }).catch(() => {
        // Ignorer les erreurs, la fenêtre est déjà créée
      });
    } else {
      // En mode production, démarrer le serveur (in-process de préférence)
      console.log('\n📦 MODE PRODUCTION: démarrage du backend...');
      try {
        // ✅ RECOMMANDÉ: In-process (plus robuste, zéro spawn)
        console.log('[BACKEND] 🔄 Tentative démarrage in-process...');
        await startBackendInProcess();
        
        // ✅ CRITIQUE: Attendre /api/health après démarrage
        console.log('[BACKEND] 🔍 Validation du backend sur /api/health...');
        const ok = await waitForServer(40); // ~20 secondes
        if (!ok) throw new Error('Backend non accessible sur /api/health après démarrage');
        console.log('[BACKEND] ✅ Backend in-process DÉMARRÉ et VALIDÉ\n');
      } catch (inProcessError) {
        // ⚠️ Fallback: spawn avec Electron en mode Node
        console.warn('[BACKEND] ⚠️  In-process échoué, fallback spawn:', inProcessError.message);
        console.warn('[BACKEND] Stack:', inProcessError.stack);
        try {
          await startServer();
          
          // ✅ CRITIQUE: Attendre /api/health après spawn aussi
          console.log('[BACKEND] 🔍 Validation du backend spawn sur /api/health...');
          const ok = await waitForServer(40);
          if (!ok) throw new Error('Backend spawn non accessible sur /api/health');
          console.log('[BACKEND] ✅ Backend spawn DÉMARRÉ et VALIDÉ\n');
        } catch (spawnError) {
          console.error('[BACKEND] ❌ Spawn aussi échoué:', spawnError.message);
          console.error('[BACKEND] Stack:', spawnError.stack);
          throw spawnError;
        }
      }
      
      try {
        console.log('[WINDOW] 🪟 Création de la fenêtre BrowserWindow...');
        createWindow();
        console.log('[WINDOW] ✅ Fenêtre créée avec succès\n');
      } catch (windowError) {
        console.error('[WINDOW] ❌ Erreur création fenêtre:', windowError);
        mainWindow = null;
      }
    }
    
    // ✅ IMPORTANT: Garder Electron ouvert même si la création de fenêtre échoue
    if (!mainWindow) {
      console.warn('⚠️  Avertissement: pas de fenêtre principale, l\'app resta active');
    }
    
    // Démarrer AI LaGrace dès que le serveur est prêt (pas de délai fixe)
    startAI().catch((err) => {
      console.error('[AI] Erreur démarrage:', err);
    });
    
  } catch (error) {
    console.error('\n');
    console.error('════════════════════════════════════════════════════════════════════');
    console.error('❌ ERREUR CRITIQUE lors du démarrage');
    console.error('════════════════════════════════════════════════════════════════════');
    console.error(`Message: ${error.message}`);
    console.error(`Stack:\n${error.stack}`);
    console.error('════════════════════════════════════════════════════════════════════\n');
    
    // ✅ ÉCRIRE DANS LE FICHIER DE LOG
    logCritical('❌ ERREUR CRITIQUE lors du démarrage');
    logCritical(`Message: ${error.message}`);
    if (error.stack) logToFile(error.stack);
    logCritical(`Voir le fichier de log complet: ${MAIN_LOG}`);
    
    // ✅ IMPORTANT: NE PAS quitter immédiatement si possible
    // Essayer de créer une fenêtre vide pour montrer l'erreur
    try {
      createWindow();
      if (mainWindow) {
        mainWindow.webContents.on('did-finish-load', () => {
          mainWindow.webContents.executeJavaScript(`
            document.body.innerHTML = '<h1 style="color:red; font-family:monospace;">❌ ERREUR DE DÉMARRAGE</h1>' +
            '<pre style="color:#ccc; font-family:monospace; margin:20px; white-space:pre-wrap; word-wrap:break-word;">${error.message}\n\nVoir les logs: ${MAIN_LOG}</pre>';
          `);
        });
        mainWindow.loadURL('data:text/html,<h1>❌ Erreur de démarrage</h1>');
      }
    } catch (e) {
      console.error('Impossible de créer une fenêtre d\'erreur:', e);
      logCritical('Impossible de créer fenêtre erreur:', e.message);
      // Seulement quitter si vraiment impossible de continuer
      process.exit(1);
    }
  }
});

// Quitter quand toutes les fenêtres sont fermées (sauf macOS)
app.on('window-all-closed', () => {
  // Arrêter AI LaGrace
  stopAI();
  
  // Arrêter le serveur quand toutes les fenêtres sont fermées
  if (serverProcess) {
    console.log('Fermeture de toutes les fenêtres, arrêt du serveur...');
    serverProcess.kill('SIGTERM');
    
    // Attendre un peu pour que le serveur se ferme proprement
    setTimeout(() => {
      if (serverProcess) {
        serverProcess.kill('SIGKILL');
        serverProcess = null;
      }
    }, 1000);
  }

  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// Gestion des contrôles IA depuis l'interface
ipcMain.handle('ai-start', async () => {
  try {
    await startAI();
    return { success: true };
  } catch (error) {
    console.error('[IPC] Erreur démarrage IA:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('ai-stop', () => {
  try {
    stopAI();
    return { success: true };
  } catch (error) {
    console.error('[IPC] Erreur arrêt IA:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('ai-status', () => {
  return {
    running: aiProcess !== null,
    pid: aiProcess ? aiProcess.pid : null
  };
});

// Réactiver la fenêtre sur macOS
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Fonction pour arrêter proprement le serveur et l'AI
function stopServer() {
  // Arrêter AI LaGrace d'abord
  stopAI();
  
  if (serverProcess) {
    console.log('Arrêt du serveur...');
    serverProcess.kill('SIGTERM');
    
    // Attendre un peu pour que le serveur se ferme proprement
    setTimeout(() => {
      if (serverProcess) {
        serverProcess.kill('SIGKILL');
        serverProcess = null;
      }
    }, 2000);
  }
}

// Arrêt propre de l'application
app.on('before-quit', async (event) => {
  // Arrêter le serveur quand l'application se ferme
  if (serverProcess) {
    event.preventDefault(); // Empêcher la fermeture immédiate
    stopServer();
    
    // Shutdown app (DB, loggers, etc.)
    if (appContext) {
      const initBridge = require('./init-bridge.cjs');
      await initBridge.shutdownApp();
    }
    
    setTimeout(() => {
      app.exit(0); // Fermer l'application après l'arrêt du serveur
    }, 2000);
  }
});

// Gestion des signaux système pour arrêter proprement
process.on('SIGINT', () => {
  console.log('\nSignal SIGINT reçu, arrêt...');
  stopServer();
  setTimeout(() => {
    app.quit();
    process.exit(0);
  }, 2000);
});

process.on('SIGTERM', () => {
  console.log('\nSignal SIGTERM reçu, arrêt...');
  stopServer();
  setTimeout(() => {
    app.quit();
    process.exit(0);
  }, 2000);
});

// Arrêt propre à la fermeture du processus
process.on('exit', () => {
  stopAI();
  if (serverProcess) {
    serverProcess.kill('SIGKILL');
  }
});

// Gestion des erreurs non gérées
process.on('uncaughtException', (error) => {
  console.error('Erreur non gérée:', error);
});
